; sprachabhängige Variablen, Nutzersprache wird ermittelt, falls nicht
; verfügbar wird Systemsprache genutzt
IniRead, Lng, %ConfigFile%, %ScriptName%, Language
If (Lng = "ERROR" OR Lng = "")
{
	; Sprache ermitteln, wenn nicht in INI festgelegt
	; User locale ermitteln
	RegRead, Lng, HKCU, Control Panel\International,Locale
	if (ErrorLevel != 1)
	{
		StringRight, Lng, Lng, 2
	}
	; alternative über Systemsprache
	else
	{
		StringRight, Lng, A_Language, 2
	}
}

If Lng = 07  ; = Deutsch (0407, 0807, 0c07 ...)
{
	lng_ID								= 0x0407
	lng_nightlyNoUpdate				= Entwicklerversion - Update nur über Installer möglich
	lng_Info								:= ScriptTitle " konfigurieren ..."
	lng_noSettingsTitle			= Einstellungsverzeichnis nicht gefunden - ac'tivAid trotzdem Starten?
	lng_noSettingsText			:= "ac'tivAid hat das Einstellungsverzeichnis nicht an der vermuteten Stelle gefunden. Wenn Sie ac'tivAid neu installiert haben wählen Sie bitte ""Ja"", ac'tivAid wird das Verzeichnis dann anlegen. Falls Sie bereits Einstellungen haben wählen Sie ""Nein"" und kopieren Sie dieses an folgende Stelle:`n"
	lng_iniNotWritableTitle			= INI-Datei nicht schreibbar - ac'tivAid trotzdem Starten?
	lng_iniNotWritableText			:= "ac'tivAid erhält keinen schreibenden Zugriff auf die INI-Datei. Dies kann der Fall sein, wenn ac'tivAid aktualisiert wird. Wenn Sie gerade aktualisieren drücken Sie bitte ""Wiederholen"", wenn dieser Dialog mehrfach auftritt, drücken Sie bitte ""Nein"" und geben Sie Schreibrechte für die Datei:`n"
	lng_downloadingActivAid			= Die aktuelle Version von ac'tivAid wird heruntergeladen ...
	lng_ProblemSolver					= Problembehebung
	lng_ProbSolvHidden				:= "Alle von " ScriptNameFull "verschobenen und minimierten Fenster wurden wiederhergestellt!"
	lng_ProbSolvResult				= Folgende Probleme wurden behoben:
	lng_ProbSolvWhy					:= "Beim Starten von " ScriptNameFull " wurden nicht wiederhergestellte Fenster gefunden."
	lng_ProbSolvNoRes					= Es wurden keine zu behebende Probleme gefunden.`nVersuchen sie evtl. %ScriptNameFull% zu deaktivieren, neu zu laden oder Erweiterungen zu deinstallieren.
	lng_update							= Auf Aktualisierung prüfen
	lng_NoUpdate						= Automatische Aktualisierung einer mit PackAndGo erzeugten Exe-Version nicht möglich.`nBitte starten Sie die Skript-Version und erzeugen Sie nach der`nAktualisierung mittels PackAndGo eine neue Exe-Version.
	lng_AutoCheckUpdtBeta			= Automatisch bei jedem Start von ac'tivAid prüfen
	lng_AutoCheckUpdt					= Jede Woche automatisch prüfen
	lng_DisableAutoUpdateOnSlowNetwork= Bei langsamer Verbindung automatisch deaktivieren
	lng_AskUpdate						= Soll eine automatische Aktualisierung durchgeführt werden?`nSie müssen dazu online sein und den Internet Explorer installiert haben.`n`nDie aktuelle Version finden Sie auch unter: www.heise.de/software/download/24593
	lng_NeedNoUpdate					= %ScriptName% ist auf dem aktuellen Stand!`nlokale Version  : %ScriptVersion%`nServer-Version:
	lng_NeedUpdate						= Es ist eine neuere Version von %ScriptNameFull% auf dem Server.`nWollen sie den Installer herunterladen?`nIhre Einstellungen bleiben bei der Installation unverändert!`n`nLokale Version:  %ScriptVersion%`nServer Version:
	lng_UpdateError					= Die aktuelle Version konnte nicht ermittelt werden, prüfen Sie ggf. ihre Internetverbindung.`nDamit die Aktualisierung funktioniert, muss der Internet Explorer installiert sein.`nBeachten Sie auch die Hinweise zu Proxy-Servern in Kapitel 3.2 der Hilfe.
	lng_UpdateFinished				= %ScriptNameFull% wurde aktualisiert und wird nun neu geladen.
	lng_UpdateSuccess					= Die Aktualisierung auf %ScriptTitle% war erfolgreich.
	lng_UpdateNewExtension			= In der Aktualisierung sind folgende neue Erweiterungen enthalten:
	lng_UpdateFailed					= Aktualisierung fehlgeschlagen. Prüfen Sie Ihre Internetverbindung und versuchen es noch einmal.`n`nDie aktuelle Version finden Sie auch unter: www.heise.de/software/download/24593
	lng_SlowNetwork					= Die Internetverbindung ist sehr langsam oder falsch konfiguriert.`nSoll die automatische Aktualisierung nun deaktiviert werden, damit ac'tivAid beim Starten nicht mehr ausgebremst wird?`n"Nein" deaktiviert die Prüfung auf langsame Verbindungen.
	lng_autostart						= %ScriptNameFull% beim Anmelden bzw. Systemstart laden
	lng_ShowFocusToolTip				= Hinweise (ToolTips) zu aktiven Eingabefeldern
	lng_reload							= %ScriptNameFull% &neu laden
	lng_More								= Mehr
	lng_deactivate						= %ScriptNameFull% &deaktivieren
	lng_deactivateM					:= lng_deactivate
	lng_TempSuspend					= Tastaturkürzel kurzfristig deaktivieren
	lng_SuspendToolTip				= Tastaturkürzel von ac'tivAid inaktiv
	lng_TrayClick						= Aktion bei Doppelklick auf das Tray-Symbol
	lng_TrayMClick						= Aktion bei Mittelklick auf das Tray-Symbol
	lng_TrayRClick						= Aktion bei Rechtsklick auf das Tray-Symbol
	lng_TrayClickOptions				= Konfiguration aufrufen|ac'tivAid de-/aktivieren|ac'tivAid neu laden|Tastaturkürzel-Übersicht|Kontextmenü aller Funktionen|Zuletzt ausgeführter AutoHotkey-Code|AutoHotkey-Variablen|AutoHotkeys Hotkey-Belegung|AutoHotkeys Hotkey-Verlauf|WindowSpy aufrufen|ac'tivAid Menü
	lng_SingleClickTrayAction		= Tray-Icon-Aktion mit einem Einfachklick ausführen
	lng_useTrayMenuIcons				= Im ac'tivAid-Menü Icons anzeigen.
	lng_ShowIconsInOptionsListBox	= In der Liste der Erweiterungen Icons anzeigen
	lng_Extension						= Erweiterung
	lng_Extensions						= Erweiterungen
	lng_Connections					= Internetverbindung
	lng_ConnectionsTab				= Internetverbindung
	lng_IgnoreApps						= Deaktivieren
	lng_ExtOff							= Alle Erweiterungen verstecken
	lng_ExtOn							= Alle Erweiterungen wieder anzeigen
	lng_ExtDeinst						= Alle Erweiterungen verstecken und Einstellungs-Datei umbenennen
	lng_ExtDeinstAsk					= Sollen wirklich alle Erweiterungen versteckt und die Einstellungs-Datei in 'ac'tivAid_ProblemSolver.ini' umbenannt werden?
	lng_SwitchExtErr					= Kein Zugriff auf das extensions-Verzeichnis mit den Erweiterungen, evtl. sind noch Skript-Dateien in einem Texteditor geöffnet!
	lng_ShowInTrayMenu				= Erweiterung im Tray-Menü anzeigen
	lng_GetKey							= Bitte eine Tastenkombination drücken`n(ESC = Abbruch, Entf = Löschen)
	lng_GetSingleKey					= Bitte eine Taste drücken`n(ESC = Abbruch, Entf = Löschen)
	lng_GetInputDevice				= Bitte eine Maustaste oder einen Joystick-Knopf drücken`n`nCursor hoch = Mausrad hoch, Cursor runter = Mausrad runter`nESC = Abbruch, Entf = Löschen
	lng_GetKeySuspendStatus0		= `n`nTastaturabfrage: ac'tivAid-Kürzel und RemapKeys berücksichtigen`n(Umschalten mit beiden Strg-Tasten)
	lng_GetKeySuspendStatus1		= `n`nTastaturabfrage: komplette Tastatur`n(Umschalten mit beiden Strg-Tasten)
	lng_AddApps							= Bitte das gewünschte Fenster auswählen und Enter drücken (ESC = Abbruch):
	lng__Debug							= AutoHotkey-Menü ins Tray-Menü einbeziehen (Window Spy, etc.)
	lng_MessageBoxTips				= Hinweisfenster statt Sprechblasenhinweise (BalloonTips)
	lng_ecmEnabled						= Kontextmenü im Explorer anzeigen (SendTo)
	lng_NoBalloonTips					= Sprechblasenhinweise deaktivieren
	lng_MainGUI							= Konfigurationsdialog
	lng_DuplicateHotkey				= ### wird schon von folgender Erweiterung verwendet:
	lng_DuplicateWinHotkey			= ##1 ist eine Standard-Tastaturkürzel von ##2.`nDerzeit hat es die Funktion:
	lng_OverwriteWinHotkey			= Soll das eingegebene Tastaturkürzel verwendet und somit das Tastaturkürzel`nvon Windows überschrieben werden?
	lng_DuplicateHotkeys				= Folgende Tastaturkürzel sind doppelt belegt. Nur dem erste Kürzel wurde eine Funktion zugewiesen. Per Doppelklick kann man direkt zur entsprechenden Erweiterung springen.
	lng_DuplicateTitle				= Konflikt bei der Tastaturkürzel-Zuweisung
	lng_DuplicateCol1					= Erweiterung
	lng_DuplicateCol2					= Tastaturkürzel
	lng_DuplicateCol3					= Funktion
	lng_DuplicateTempHotkey			= ### wurde gerade zugewiesen,`njedoch noch nicht gespeichert
	lng_OverwriteDupHotkey			= Soll das eingegebene Tastaturkürzel verwendet und somit das Tastaturkürzel`naus der oben aufgeführten Erweiterung entfernt werden?
	lng_Chapter							= Kapitel:
	lng__Devel							= Entwicklermodus (ac'tivAid wird automatisch neu geladen, wenn eine Skript-Datei gespeichert wurde)
	lng_WritingSettings				= Einstellungen werden gespeichert
	lng_requires						= benötigt
	lng_requiresAddMsg				= Diese Erweiterung funktioniert nur,`nwenn folgende Erweiterungen installiert sind:`n
	lng_requiresRemMsg				= Diese Erweiterung kann nicht deinstalliert werden,`nda sie von folgenden Erweiterungen benötigt wird:`n
	lng_getClassMsg					= Bitte den Mauszeiger über das gewünschte Fensterelement oder`ndie Titelleiste (= komplettes Fenster) bewegen und Enter drücken.`n(ESC = Abbruch)
	lng_getWindowClassMsg			= Bitte den Mauszeiger über das gewünschte`nFenster bewegen und Enter drücken.`n(ESC = Abbruch)
	lng_Loading							= %ScriptNameFull% wird neu geladen ...
	lng_Apply							= &Übernehmen
	lng_installed						= installierte
	lng_available						= verfügbare (deinstallierte)
	lng_exit								= &Beenden
	lng_Left								= linke
	lng_Right							= rechte
	lng_Middle							= mittlere
	lng_MouseButton					= Maustaste
	lng_Key								= Taste
	lng_KbRelease						= loslassen
	lng_KbAppsKey						= Kontextmenütaste
	lng_KbWin							= Windows
	lng_KbAlt							= Alt
	lng_KbShift							= Umschalt
	lng_KbShiftShort					= Umsch
	lng_KbCtrl							= Strg
	lng_KbCapsLock						= Feststelltaste
	lng_KbNumpad						= Ziffernblock
	lng_KbNumpadShort					= Num
	lng_KbScrollLock					= Rollen
	lng_KbPgUp							= Bild hoch
	lng_KbPgDn							= Bild runter
	lng_KbEnd							= Ende
	lng_KbDot							= Komma
	lng_KbDel							= Entf
	lng_KbHome							= Pos1
	lng_KbIns							= Einfg
	lng_KbClear							= Löschen
	lng_KbPrintScreen					= Druck
	lng_KbCtrlBreak					= Pause/Untbr
	lng_KbBackspace					= Löschen
	lng_KbSpace							= Leertaste
	lng_KbEnter							= Enter
	lng_KbTab							= Tab
	lng_KbPause							= Pause/Untbr
	lng_KbCurUp							= Cursor hoch
	lng_KbCurDown						= Cursor runter
	lng_KbCurLeft						= Cursor links
	lng_KbCurRight						= Cursor rechts
	lng_KbHelp							= Hilfe
	lng_KbSleep							= Standby
	lng_KbBrowser_Back				= Browser Zurück
	lng_KbBrowser_Forward			= Browser Vorwärts
	lng_KbBrowser_Refresh			= Browser Aktualisieren
	lng_KbBrowser_Stop				= Browser Abbrechen
	lng_KbBrowser_Search				= Browser Suchen
	lng_KbBrowser_Favorites			= Browser Favoriten
	lng_KbBrowser_Home				= Browser Startseite
	lng_KbVolume_Mute					= Lautstärke Stumm
	lng_KbVolume_Down					= Lautstärke Leiser
	lng_KbVolume_Up					= Lautstärke Lauter
	lng_KbMedia_Next					= Media Vor
	lng_KbMedia_Prev					= Media Zurück
	lng_KbMedia_Stop					= Media Stop
	lng_KbMedia_Play_Pause			= Media Play/Pause
	lng_KbLaunch_Mail					= Start Mail
	lng_KbLaunch_Media				= Start Media
	lng_KbLaunch_App1					= Start Anwendung1
	lng_KbLaunch_App2					= Start Anwendung2
	lng_KbWheelUp						= Mausrad hoch
	lng_KbWheelDown					= Mausrad runter
	lng_KbLButton						= linke Maustaste
	lng_KbRButton						= rechte Maustaste
	lng_KbMButton						= mittlere Maustaste
	lng_Readme							= Hilfe
	lng_FAQ								= Bitte beachten Sie auch die häufig gestellten Fragen auf www.heise.de/software/download/24593
	lng_Changelog						= Änderungen
	lng_ViewChangelog					= Was ist neu?
	lng_Browse							= &Durchsuchen ...
	lng_CustomWorkingDir				= Arbeitsverzeichnis
	lng_activated						= aktiviert
	lng_activate						= aktivieren
	lng_deactivated					= deaktiviert
	lng_OK								= &OK
	lng_cancel							= A&bbrechen
	lng_Close							= &Schließen
	lng_Default							= &Zurücksetzen
	lng_Hotkey							= Tastaturkürzel
	lng_Hotkeys							= Tastaturkürzel
	lng_Command							= Befehl
	lng_SettingsMenu					= 8
	lng_DefaultSettings				= ### auf Standard-Einstellungen zurücksetzen
	lng_ExportSettings				= ###-Einstellungen exportieren
	lng_ImportSettings				= ###-Einstellungen importieren
	lng_AddSettings					= ###-Einstellungen hinzufügen
	lng_ResetWindows					= Alle Fenster von ### zurücksetzen
	lng_AskResetWindows				= Sollen wirklich alle Fenster von ### zurückgesetzt werden?
	lng_ExportAsk						= Sollen die Einstellungen der derzeit sichtbaren Erweiterung exportiert werden?`nÄnderungen, die hier noch nicht mit OK oder Übernehmen bestätigt wurden, werden nicht exportiert.
	lng_ImportAsk						= Beim Importieren werden alle Einstellungen der sichtbaren Erweiterung überschrieben.`nSollen die Einstellungen wirklich importiert werden?
	lng_ImportAsk2						= Beim Importieren werden alle Einstellungen der sichtbaren Erweiterung überschrieben.`nÄnderungen die hier und in anderen Erweiterungen noch nicht mit OK oder Übernehmen bestätigt wurden, werden nicht übernommen.`nSollen die Einstellungen wirklich importiert werden?
	lng_AddAsk							= Sollen die Einstellungen wirklich hinzugefügt werden?`nEs werden nur nicht vorhandene Einträge hinzugefügt.
	lng_ImportImpossible				= Diese Einstellungs-Datei passt nicht zu der Erweiterung!
	lng_SaveAllSettings				= Alle Einstellungs-Dateien in einem Ordner sichern
	lng_LoadAllSettings				= Einstellungs-Dateien aus einem Ordner laden
	lng_SaveAllAsk						= Sicherungsordner auswählen, wo die gesamten Einstellungen gesichert werden. Nicht bestätigte Änderungen (OK/Übernehmen) werden nicht gesichert.
	lng_LoadAllAsk						= Ordner mit den gesicherten Einstellungsdateien auswählen. ALLE AKTUELLEN EINSTELLUNGEN WERDEN ÜBERSCHRIEBEN!
	lng_DefaultMsg						= Sollen die Einstellungen und Kürzel dieser Erweiterung auf die Standard-Werte zurückgesetzt werden?`nAchtung: In anderen Erweiterungen gehen nicht mit OK oder Übernehmen bestätigte Einstellungen verloren.
	lng_SettingsNotApplied			= ac'tivAid muss neu geladen werden, nicht bestätigte`nÄnderungen (OK/Übernehmen) werden nicht gesichert.`n`nMöchten Sie fortfahren?
	lng_PleaseApplySettings			= Bitte bestätigen Sie zuvor alle vorgenommenen Einstellungen mit OK oder Übernehmen!
	lng_ExtensionManagerHelp		= Installierte Erweiterungen müssen unter Umständen noch im Konfigurationsfenster oder im Kontextmenü des Tray-Symbols aktiviert werden.`n`nAlle bei 'Verfügbare Erweiterungen' aufgelisteten Erweiterungen werden nicht mit ac'tivAid geladen und müssen zur Verwendung hier installiert werden.
	lng_DuplicateExtensions			= Folgende Erweiterungen haben den gleichen Namen. Eine der Dateien muss angepasst oder gelöscht werden
	lng_Settings						:= ScriptName
	lng_IsInList						= Das ausgewählte Verzeichnis befindet sich schon in der Liste!
	lng_HasSubfolder					= Vom ausgewählte Verzeichnis befinden sich schon Unterverzeichnisse in der Liste!`nDiese müssen vorher entfernt werden.
	lng_IsSubfolder					= Das ausgewählte Verzeichnis ist ein Unterverzeichnis von:
	lng_EnableDisable					= Erweiterung aktivieren/deaktivieren
	lng_ShowHotkeyList				= Tastaturkürzel-Übersicht einblenden
	lng_HotkeyListAOT					= Tastaturkürzel-Übersicht immer im Vordergrund halten
	lng_CreatingHotkeyList			= Tastaturkürzel-Übersicht wird aufgebaut ...
	lng_ShowMainContextMenu			= Kontextmenü mit allen Funktionen
	lng_SilentUpdate					= Keine Sicherheitsabfrage bei der Aktualisierungs-Prüfung
	lng_NoSoundBeepInSearch			= Kein PC-Speaker-Signalton bei der Suchfunktion (Hilfe, QuickNote ...) verwenden
	lng_NoTrayIcon						= Programm-Symbol (Tray-Icon) in der Taskleiste verstecken`nAchtung: Der Konfigurationsdialog ist dann nur noch über das oben aufgeführte Tastaturkürzel zu erreichen.
	lng_Betatester						= Auch Beta-Versionen beziehen, welche allerdings unerwartetes Verhalten aufweisen könnten.
	lng_ManualUpdate					= manuell aktualisieren
	lng_ManualUpdateText				= Falls automatische Updates z.B. durch einen Proxy-Server verhindert werden, müssen Sie die aktuelle Version manuell herunterladen und installieren. Die aktuelle Version finden Sie unter folgender Adresse:
	lng_OpenURLAndExit				= Webseite öffnen und ac'tivAid beenden
	lng_SelectLanguage				= Sprache wählen / select language
	lng_RunAsAdmin						= ac'tivAid mit Administrator-Rechten starten
	lng_NeedAdminRights				= ac'tivAid benötigt Administrator-Rechte
	lng_NeedUserPass					= Bitte das Passwort des aktuellen Benutzers eingeben
	lng_LeaveAdmin						= Administrator-Modus verlassen
	lng_LeaveAdminCantReload		= ac'tivAid wird nach dem Verlassen des Administrator-Modus nicht automatisch neu geladen.`nSie müssen ac'tivAid manuell neu starten.
	lng_UserMode00						= Einzelbenutzer-Modus aktivieren
	lng_UserMode10						= Einzelbenutzer-Modus, Admin
	lng_UserMode01						= Mehrbenutzer-Modus aktivieren
	lng_UserMode11						= Mehrbenutzer-Modus, Admin
	lng_UserMode001					= USB/Portable Standard-Modus aktivieren
	lng_UserMode101					= USB/Portable Standard-Modus, Admin
	lng_UserMode011					= USB/Portable Mehr-Computer-Modus aktivieren
	lng_UserMode111					= USB/Portable Mehr-Computer-Modus, Admin
	lng_CheckYourFolderOptions		= In den Ordneroptionen muss eingestellt werden, dass im`nFenstertitel oder in der (sichtbaren!) Adressleiste der`nvollständige Pfad angezeigt wird. Da der Fenstertitel im`nExplorer eine Längenbeschränkung hat, empfiehlt sich`ngenerell die Adressleiste.
	lng_ChangeDirFailed				= Für den Verzeichniswechsel muss ein Explorerfenster mit Adressleiste oder ein Dateidialog aktiv sein.
	lng_FolderDoesNotExist			= Das Verzeichnis existiert nicht:
	lng_AdminAttention				:= "  Achtung: ac'tivAid läuft mit Administrator-Rechten.`n  Falls Sie in Windows nicht mit Administrator-Rechten arbeiten,`n  sollten Sie den Administrator-Modus so bald wie möglich verlassen.`n  Nutzen Sie dazu den entsprechenden Menüpunkt im ac'tivAid-Menü!"
	lng_AdminAttentionAsk			= Möchten Sie ac'tivAid direkt neu laden und den`n  Admin-Modus verlassen?
	lng_DisableToggleLayout			= Das System-Tastaturkürzel für den Eingabegebietsschemawechsel (meist Alt+Shift) ist aktiv.`nIm Zusammenhang mit ac'tivAid (bzw. AutoHotkey) kann es dabei zu einem unvorhergesehenen Tastaturlayout-Wechsel kommen.`nEs handelt sich hierbei um ein altbekanntes Problem, auf welches nur einmal hingewiesen wird.`n`nSoll ac'tivAid das Systemkürzel für Sie deaktivieren? (Registry wird verändert)
	lng_AskUninstall					= Soll ac'tivAid samt allen Einstellungen der Benutzer deinstalliert werden?`n`nFolgende Verzeichnisse werden entfernt:`n
	lng_UninstallFinished			= ac'tivAid wurde deinstalliert!`nDateien, die nicht gelöscht werden konnten, werden nach einem Neustart entfernt.
	lng_CreateUninstaller			= ac'tivAid wird zum ersten mal ausgeführt.`n`nSoll ein Programmgruppe eingerichtet und ac'tivAid unter Systemsteuerung/Software eingetragen werden,`ndamit es später einfach deinstalliert werden kann?`n`nDies erfordert Zugriff auf die Registry.
	lng_noUninstallerInsideActivaid			= Es gibt keinen Uninsaller mehr innerhalb von ac'tivAid.
	lng_by								= von
	lng_Help								= Hilfe
	lng_ContextHelp					= Hilfe zu ###
	lng_activAidHomepage				= Offizielle Webseite von ac'tivAid aufrufen
	lng_Bugtracker						= Support-Webseite aufrufen (Bugtracker)
	lng_Contact							= E-Mail-Kontakt (activaid@heise.de)
	lng_About							= Über %ScriptNameFull% ...
	lng_about_main_developer		= Hauptentwickler`n(Kern und Erweiterungen)
	lng_about_ext_developer			= Entwickler von Erweiterungen
	lng_OpenSettingsDir				= Verzeichnis 'settings' öffnen
	lng_CopySettingsToSingle		= Alle Einstellungen in den Einzelbenutzer-Modus exportieren
	lng_CopySettingsToSingleAsk	= Durch das Exportieren der Einstellungen zum Einzelbenutzer-Modus`nwerden dort alle Einstellungen überschrieben.`nSollen die Einstellungen exportiert werden?
	lng_CopyUSBSettingsToSingle	= Alle Einstellungen in den USB/Portable Standard-Modus exportieren
	lng_CopyUSBSettingsToSingleAsk= Durch das Exportieren der Einstellungen zum USB/Portable Standard-Modus`nwerden dort alle Einstellungen überschrieben.`nSollen die Einstellungen exportiert werden?
	lng_CopySettingsToUser			= Alle Einstellungen aus dem Einzelbenutzer-Modus importieren
	lng_CopySettingsToUserAsk		= Durch das Importieren der Einstellungen vom Einzelbenutzer-Modus`nwerden alle derzeitigen Einstellungen dieses Benutzers überschrieben.`nSollen die Einstellungen importiert werden?
	lng_CopySettingsFromUser		= Alle Einstellungen des Benutzers %A_Username% importieren
	lng_CopySettingsFromUserAsk	= Durch das Importieren der Einstellungen des Benutzers %A_Username%`nin den Einzelbenutzer-Modus werden alle derzeitigen Einstellungen überschrieben.`nSollen die Einstellungen importiert werden?
	lng_CopyUSBSettingsToUser		= Alle Einstellungen aus dem USB/Portable Standard-Modus importieren
	lng_CopyUSBSettingsToUserAsk	= Durch das Importieren der Einstellungen vom USB/Portable Standard-Modus`nwerden alle vorhandenen Einstellungen für diesen Computer überschrieben.`nSollen die Einstellungen importiert werden?
	lng_CopyUSBSettingsFromUser	= Alle Einstellungen aus ComputerSettings/%A_Computername% importieren
	lng_CopyUSBSettingsFromUserAsk= Durch das Importieren der Einstellungen von ComputerSettings/%A_Computername%`nin den USB/Portable Standard-Modus werden alle vorhandenen Einstellungen überschrieben.`nSollen die Einstellungen importiert werden?
	lng_AlternativeTrayMenu			= Einträge im Tray-Menü rufen die Konfiguration der entsprechenden Erweiterung auf
	lng_AddUninstaller				= Deinstallations-Eintrag und ac'tivAid-Programmgruppe anlegen
	lng_RemoveUninstaller			= Deinstallations-Eintrag und ac'tivAid-Programmgruppe entfernen
	lng_AddUninstallerFailure		= Deinstallations-Eintrag und ac'tivAid-Programmgruppe konnten nicht angelegt werden.`nStarten Sie ac'tivAid ggf. im Administrator-Modus.
	lng_RemoveUninstallerFailure	= Deinstallations-Eintrag und ac'tivAid-Programmgruppe konnten nicht entfernt werden.`nStarten Sie ac'tivAid ggf. im Administrator-Modus.
	lng_AddUninstallerSuccess		= Deinstallations-Eintrag und ac'tivAid-Programmgruppe wurden angelegt.
	lng_RemoveUninstallerSuccess	= Deinstallations-Eintrag und ac'tivAid-Programmgruppe wurden entfernt.
	lng_None								= (keine)
	lng_DisableOthers					= Alle anderen Erweiterungen deaktivieren
	lng_EnableAll						= Alle Erweiterungen aktivieren
	lng_RemoveFromGUI					= ### aus dem Konfigurationsfenster entfernen
	lng_RemovedExtensions			= Entfernte Erweiterungen wiederherstellen...
	lng_Search							= Suchbegriff
	lng_PortableExe					= Vermutlich wollten Sie Portable ac'tivAid starten, haben aber versehentlich "ac'tivAid.ahk" gestartet. Um in den portablen Modus zu gelangen, müssen Sie "Portable_ac'tivAid.exe" ausführen! Diese Meldung wird durch Umbenennen dieser Datei unterdrückt.
	lng_WrongAHKVersion				= AutoHotkey %neededAHKversion% oder höher wird benötigt.`nBitte installieren Sie die aktuelle Version von AutoHotkey.`n`nBei einer automatischen Aktualisierung von ac'tivAid`nwird AutoHotkey ebenfalls aktualisiert.
	lng_BackupOnUpdate				= Vor der Aktualisierung ein Backup vom ac'tivAid-Verzeichnis anlegen
	lng_Show								= Zeigen ...
	lng_On								= An
	lng_Off								= Aus
	lng_AnotherActivAidActive		= Es läuft bereits eine anderer ac'tivAid-Prozess.`nMehrere gleichzeitig laufende Prozesse führen zu unvorhersehbarem Verhalten.`nMöchten Sie wirklich einen weiteren ac'tivAid-Prozess starten?
	lng_NewSettingsDirForVista		= Ab Windows Vista darf ein Programm nicht mehr in das eigene Verzeichnis im Programme Ordner schreiben.`nDie Einstellungen für den Einzelbenutzer-Modus werden nun von:`n%A_ScriptDir%\settings`nnach:`n%A_AppDataCommon%\ac'tivAid\settings`nkopiert.
	lng_NoExtensionsInstalled		= <-+------------------------------------------------------------------------+`n  | Es wurden noch keine Erweiterungen in ac'tivAid installiert. Ohne      |`n  | Erweiterungen bietet ac'tivAid keine nützlichen Funktionen. Sie können |`n  | links in der Kategorieliste die Kategorie 'Erweiterungen' auswählen      |`n  | und dort Erweiterungen installieren.												|`n  +------------------------------------------------------------------------+`n`n`n

	lng_Second							= Sekunde
	lng_Seconds							= Sekunden
	lng_Minute							= Minute
	lng_Minutes							= Minuten
	lng_Hour								= Stunde
	lng_Hours							= Stunden
	lng_Day								= Tag
	lng_Days								= Tage
	lng_Month							= Monat
	lng_Months							= Monate
	lng_Year								= Jahr
	lng_Years							= Jahre

	lng_Statistics						= Statistik und Informationen
	lng_StatFirstLaunch				= Erster Programmstart
	lng_StatLastLaunched				= Letzter Programmstart
	lng_StatLaunchCount				= Programmstarts ingesamt
	lng_StatReloadCount				= Neu geladen insgesamt
	lng_StatUpdateCount				= Aktualisierungen insgesamt
	lng_StatExitCount					= Regulär beendet
	lng_StatTotalTime					= Laufzeit insgesamt
	lng_StatSessionTime				= Laufzeit aktuelle Sitzung
	lng_StatLongestSession			= Längste Sitzung
	lng_StatVersion					= ac'tivAid-Version
	lng_StatAHKVersion				= AutoHotkey-Version
	lng_StatOS							= Betriebssystem
	lng_StatCompOS							= Kompatibiltätsmodus
	lng_StatUser						= Benutzername
	lng_StatComputer					= Computername
	lng_StatIP							= IP-Adresse
	lng_StatCompiled					= , kompiliert
	lng_StatMode						= Modus
	lng_StatSettingsDir				= Ordner mit Einstellungsdateien
	lng_StatWriteLocked				= (schreibgeschützt oder keine Schreibrechte)
	lng_StatExtendRButton			= Erweitert rechte Maustaste
	lng_StatExtendMButton			= Erweitert mittlere Maustaste
	lng_StatLoadingTime				= Ladezeit (Dauer)
	lng_StatMainGuiBuildTime		= Aufbau Konfigurationsfenster
	lng_StatNumOfExtensions			= Installierte Erweiterungen
	lng_Network							= Netzwerk
	lng_AdditionalSettings			= Weitere Optionen
	lng_CleanINI						= Einstellungsdatei aufräumen
	lng_CleanINIAsk					= Die Einstellungsdatei wird gelöscht und neu angelegt.`nac'tivAid speichert dabei alle Einstellungen der installierten`nErweiterungen in die frische Einstellungs-Datei und wird danach neu geladen.`nEinstellungen nicht installierter Erweiterungen gehen dabei verloren.

	lng_ExtensionConflict			= Es konnten nicht alle installierten Erweiterungen geladen werden.`nac'tivAid wird nun automatisch neu geladen, um das Problem zu beheben.
	lng_ExtensionConflictDuplicates= Eine oder mehrere Erweiterungen sind doppelt installiert. `nac'tivAid wird nun automatisch neu geladen, um das Problem zu beheben.
	lng_ExtensionMissingQuickNote	= Mindestens ein QuickNote Script konnte nicht gefunden werden. Die Duplikation des Originalscripts wird versucht.
	lng_StatisticsToClipboard		= In die Zwischenablage kopieren (inkl. weiterer Infos)
	lng_ReloadFailed					= ac'tivAid konnte nicht neu geladen werden.`nVermutlich ist ein Fehler aufgetreten oder ac'tivAid ist beschäftigt.

	lng_winHK_ShowExplorer			= Neues Explorerfenster
	lng_winHK_ShowStartMenu			= Startmenü einblenden
	lng_winHK_ShowContextMenu		= Kontextmenü einblenden
	lng_winHK_ShowRunDialog			= Ausführen-Dialog einblenden
	lng_winHK_MinimizeAllWindows	= Alle Fenster minimieren
	lng_winHK_RestoreAllWindows	= Alle Fenster wiederherstellen
	lng_winHK_ToggleDesktop			= Desktop anzeigen
	lng_winHK_SetFocusToSysTray	= Fokus auf Systray legen
	lng_winHK_LockWorkstation		= Arbeitstation sperren
	lng_winHK_ShowExplorerFindDialog= Neues Explorer-Suchfenster
	lng_winHK_OpenUtilityManager	= Hilfsprogramm-Manager aufrufen
	lng_winHK_OpenWindowsHelp		= Windows-Hilfe aufrufen
	lng_winHK_OpenSystemProperties= Systemeigenschaften aufrufen
	lng_winHK_CycleTaskbarButtons	= Fokus auf Taskleisten-Schaltfläche
	lng_winHK_TaskSwitcher			= Taskwechsler
	lng_winHK_TopWindowToBottom	= Oberstes Fenster nach hinten legen
	lng_winHK_BottomWindowToTop	= Hinterstes Fenster noch vorne holen
	lng_winHK_CloseWindow			= Fenster schließen
	lng_winHK_ShowTaskmanager		= Task-Manager aufrufen
	lng_winHK_ScreenShotToClipboard= Bildschirmfoto in die Zwischenablage
	lng_winHK_WindowShotToClipboard= Foto vom aktiven Fenster in die Zwischenablage
	lng_winHK_CopyToClipboard		= In die Zwischanblage kopieren
	lng_winHK_CutToClipboard		= In die Zwischanblage ausschneiden
	lng_winHK_PasteFromClipboard	= Aus der Zwischanblage einfügen
	lng_winHK_NewFile					= Neue Datei
	lng_winHK_SaveFile				= Datei speichern
	lng_winHK_OpenFile				= Datei öffnen
	lng_winHK_PrintFile				= Datei drucken
	lng_winHK_Undo						= Rückgängig
	lng_winHK_SelectAll				= Alles markieren
	lng_winHK_Find						= Suchen
	lng_winHK_CloseTabOrChildWindow= Tab oder Kind-Fenster schließen
	lng_winHK_OpenHelp				= Hilfe aufrufen
	lng_winHK_SetFocusToMenuBar	= Fokus auf Menüleiste
	lng_winHK_ShowSystemMenu		= Systemmenü einblenden
	lng_winHK_DefocusOrClose		= Fokus entfernen oder Fenster schließen/abbrechen
	lng_winHK_InsertTabOrCycleControls= Tabulator einfügen oder Eingabefeld wechseln
	lng_winHK_CycleTabsOrChildWindows= Tab oder Kind-Fenster wechseln
	lng_winHK_Enter					= Return
	lng_winHK_Space					= Leertaste
	lng_winHK_MoveCursor				= Cursor bewegen
	lng_winHK_MoveCursorAndSelect	= Cursor bewegen und Markierung erweitern
	lng_winHK_Backspace				= Löschen
	lng_winHK_Delete					= Entfernen
	lng_winHK_DeletFileInExplorer	= Im Explorer: Datei löschen
	lng_winHK_DeleteFileOrSelection	= Datei oder Auswahl löschen
	lng_VarDump							= Interne Variablen anzeigen

	lng_GlobalProxySettings			= Globale Proxy-Einstellungen
	lng_ProxyType						= Typ
	lng_ProxyHistory					= Verlauf
	lng_ProxyHistoryHeaders			= URL|Lokal|Zeit|Geschw.
	lng_UseProxy						= Proxy für ### verwenden
	lng_GlobalDownloadFolder		= Standard Downloadverzeichnis
	lng_Username						= Benutzer
	lng_Password						= Kennwort

	tooltip_Hotkey_					= Anklicken, um ein Tastaturkürzel zuzuweisen.`nMit Shift oder Alt anklicken, um eine Maustaste`noder einen Joystickknopf zuzuweisen.
	tooltip_8							= 'Pfeil'-Menü mit weiteren Funktionen
	tooltip_AutoUpdate				= Die automatische Prüfung erfolgt beim Skriptstart und zeigt ggf. eine Sicherheitsabfrage an.
	tooltip_Betatester				= Beta-Versionen erscheinen in unregelmäßigen Abständen und teilweise mehrmals täglich.`nHäufig sind in Beta-Versionen schon neue Funktionen enthalten,`nwelche aber womöglich noch instabil laufen.
	tooltip_Autostart					= Aus = Entfernt die Verknüpfung aus dem Autostart-Ordner`nAn = Es wird eine Verknüpfung zu ac'tivAid im Autostart-Ordner angelegt bzw. entfernt.`nGrau/Grün = Es wird zusätzlich der Parameter 'nosplash' mit angegeben, womit der Startbildchirm nicht angezeigt wird.
	tooltip_AlternativeTrayMenu	= Die Einträge im Tray-Menü de-/aktivieren nicht mehr eine Erweiterung,`nsondern es wird direkt ein vereinfachter Konfigurationsdialog aufgerufen,`nwelche schneller aufgebaut wird als der komplette Konfigurationsdialog.`nBei jeder Erweiterung besteht die Möglichkeit zu entscheiden, ob sie im Tray-Menü aufgeführt wird.
	tooltip_Devel						= Der Entwicklermodus überwacht alle Skriptdateien innerhalb des ac'tivAid-Verzeichnisses`nund lädt ac'tivAid automatisch neu, falls ein Skript verändert wurde.`nDamit ist gewährleistet, dass Änderungen an Erweiterungen sofort getestet werden können.`nDiese Option erhöht die Festplatten-Auslastung und kann zu Leistungseinbußen führen.

	tooltip_]]							= Alle verfügbaren Erweiterungen installieren
	tooltip_[[							= Alle installierten Erweiterungen deinstallieren
	tooltip_]							= Ausgewählte Erweiterung installieren
	tooltip_[							= Ausgewählte Erweiterung deinstallieren

	tooltip_searchTermReadme		= Suchbegriff, welcher direkt bei der Eingabe gesucht wird.`nF3: weiter suchen  -  Shift+F3: rückwärts suchen
	tooltip_searchTermChangeLog	= %tooltip_searchTermReadme%
	tooltip_searchTermContextHelp	= %tooltip_searchTermReadme%
	tooltip_searchTermHotkeyList	= %tooltip_searchTermReadme%
	tooltip_searchButtonReadme		= %tooltip_searchTermReadme%
	tooltip_searchButtonChangeLog	= %tooltip_searchTermReadme%
	tooltip_searchButtonContextHelp	= %tooltip_searchTermReadme%
	tooltip_searchButtonHotkeyList	= %tooltip_searchTermReadme%

	AdminGroup							= Administratoren

	ReadMeFile							= %A_ScriptDir%\ac'tivAid LiesMich.txt
	ChangeLogFile						= %A_ScriptDir%\ac'tivAid Änderungen.txt

	lng_useGdiPlus						= GDI+ für Grafikeffekte benutzen (Betriebssysteme älter als WinXP benötigen gdiplus.dll)
	lng_sub_gdip_configGui			= GDI+ konfigurieren
	lng_gdip_backgroundColor		= Hintergrundsfarbe
	lng_gdip_backgroundColor2		= Hintergrundsfarbe 2
	lng_gdip_borderColor				= Rahmenfarbe
	lng_gdip_rounding					= Rundung
	lng_gdip_trans						= Transparenz
	lng_gdip_osd						= Aussehen
	lng_gdip_generalSettings		= Optionen
	lng_gdip_fontFamily				= Text
	lng_gdip_fontFamilyTitle		= Titel
	lng_gdip_fontFamilyHeader		= Überschrift
	lng_gdip_fontSize					= Größe
	lng_gdip_fontColor				= Farbe
	lng_gdip_monitor					= Monitor
	lng_gdip_monitorList				= Hauptmonitor|Maus|Aktives Fenster
	lng_gdip_posHorList				= Links|Mitte|Rechts
	lng_gdip_posVerList				= Oben|Mitte|Unten
	lng_gdip_position					= Position
	lng_OSDTips							= OSD statt Sprechblasenhinweise (BalloonTips)
	lng_OSDIcons						= OSD-Icons anzeigen

	lng_GdiPnotFoundTitle			= GDI+ wurde nicht gefunden
	lng_GdiPnotFound					= Bitte laden Sie die gdiplus.dll aus dem Internet herunter und speichern sie unter %A_WinDir%\System32.`nJetzt Browser mit Downloadseite öffnen?

	lng_playSound						= Sound abspielen
}
else			; = other languages (english)
{
	lng_ID								= 0x0400
	lng_nightlyNoUpdate				= Developer Version - Update only using the Installer
	lng_Info								= configure %ScriptTitle% ...
	lng_noSettingsTitle			= Settings directory not found - continue loading ac'tivAid anyway?
	lng_noSettingsText			:= "ac'tivAid did not find the settings directory at the expected location. If you just installed ac'tivAid please choose ""Yes"", ac'tivAid will create the directory for you. If you already have settings from a previous installation please choose ""No"" and copy the settings to the following directory:`n"
	lng_iniNotWritableTitle			= INI file not writeable - continue loading ac'tivAid anyway?
	lng_iniNotWritableText			:= "ac'tivAid is not able to get write access to the main ini file. This can occur on updating ac'tivAid. If you are updating ac'tivAid please press ""Yes"", when this dialog occurs multipe times, press ""No"" and check the write protection of file`n"

	lng_downloadingActivAid			= Downloading the newest version of ac'tivAid ...
	lng_ProblemSolver					= resolve keyboard and mouse-problems
	lng_ProbSolvHidden				= All by %ScriptNameFull%' hidden windows have been restored!
	lng_ProbSolvResult				= The following problems have been solved:
	lng_ProbSolvWhy					= %ScriptNameFull% has found some hidden windows.
	lng_ProbSolvNoRes					= No problems found.`nTry to deactivate or reload %ScriptNameFull% or uninstall all extensions.
	lng_update							= check for online-updates
	lng_NoUpdate						= Automatic updates are not possible with an self created exe-Version (PackAndGo).`nPlease start the script-version and recreate the exe with PackAndGo after updating the script-version.
	lng_AutoCheckUpdtBeta			= Automatically check every script-launch
	lng_AutoCheckUpdt					= Automatically check every week
	lng_DisableAutoUpdateOnSlowNetwork = Disable on slow network connection
	lng_AskUpdate						= Should the script check for an update?`nYou have to be online and Internet Explorer has to be installed.`n`nA new version could also be found at: http://www.heise.de/ct/activaid
	lng_NeedNoUpdate					= %ScriptName% is already up-to-date!`nlocal version   : %ScriptVersion%`nserver version:
	lng_NeedUpdate						= There's a more recent version of %ScriptNameFull% available!`nDo you want to download the installer now?`nYour settings remain unaffected during installation!`n`nLocal version  : %ScriptVersion%`nServer version:
	lng_UpdateError					= Could not get the current version, please check your internet connection.`nInternet Explorer must be installed for this function to work.`nRemember that ac'tivAid uses also the Proxy settings from Internet Explorer.
	lng_UpdateFinished				= %ScriptNameFull% has been updated, it will be reloaded now.
	lng_UpdateSuccess					= Update successful: %ScriptTitle%
	lng_UpdateNewExtension			= The update has installed the following new extensions:
	lng_UpdateFailed					= The downloaded file is not correct, please try it again later.
	lng_SlowNetwork					= Your internet connection is very slow.`nShould the automatic update be disabled to avoid slow starting of ac'tivAid?`nChoosing "No" will disable checking for slow connection.
	lng_autostart						= Load %ScriptNameFull% at login or system-start
	lng_ShowFocusToolTip				= Show tooltips for focused fields
	lng_reload							= &Reload %ScriptNameFull%
	lng_More								= More
	lng_deactivate						= &Deactivate %ScriptNameFull%
	lng_deactivateM					= %lng_deactivate%
	lng_TempSuspend					= Temporary disable hotkeys
	lng_SuspendToolTip				= ac'tivAid's hotkeys temporary disabled
	lng_TrayClick						= Action for double-click on tray icon
	lng_TrayMClick						= Action for middle-click on tray icon
	lng_TrayRClick						= Action for right-click on tray icon
	lng_TrayClickOptions				= Show configuration|de-/activate ac'tivAid|reload ac'tivAid|overview of all hotkeys|context menu with all functions|ListLines|ListVars|ListHotkeys|KeyHistory|WindowSpy|ac'tivAid-Menu
	lng_SingleClickTrayAction		= Use single click for tray icon actions
	lng_useTrayMenuIcons				= Show icons in ac'tivAid's tray menu
	lng_ShowIconsInOptionsListBox	= Show icons in the extension list
	lng_Extension						= Extension
	lng_Extensions						= Extensions
	lng_Connections					= Internet connections
	lng_ConnectionsTab				= Internetconnections
	lng_IgnoreApps						= Deactivate
	lng_ExtOff							= Hide all extensions
	lng_ExtOn							= Show all extensions
	lng_ExtDeinst						= Hide all extensions and rename the settings-file
	lng_ExtDeinstAsk					= Do you really want to hide all extensions and rename the settings-file to 'ac'tivAid_ProblemSolver.ini'?
	lng_SwitchExtErr					= No access to the extensions-folder, maybe you have files open!
	lng_ShowInTrayMenu				= Visible in tray-menu
	lng_GetKey							= Please press a hotkey`n(ESC = cancel, Del = delete)
	lng_GetSingleKey					= Please press a key`n(ESC = cancel, Del = delete)
	lng_GetInputDevice				= Please press a mouse or joystick button`n`nCursor up = Wheel up, Cursor down = Wheel down`nESC = cancel, Del = delete
	lng_GetKeySuspendStatus0		= `n`nKeyboard mode: respect ac'tivAid hotkeys and RemapKeys`n(Switch with both Ctrl keys)
	lng_GetKeySuspendStatus1		= `n`nKeyboard mode: native keyboard`n(Switch with both Ctrl keys)
	lng_AddApps							= Please activate a window and press Enter`n(ESC = cancel):
	lng__Debug							= Include AutoHotkey-menu in tray-menu (for debugging)
	lng_MessageBoxTips				= Message boxes instead of balloon tips
	lng_ecmEnabled						= Show contextmenu in Explorer (SendTo)
	lng_SilentUpdate					= No confirmation message when checking for updates
	lng_NoSoundBeepInSearch			= Disable pc speaker beep for the search funciton (Help, QuickNote ...)
	lng_NoBalloonTips					= No BalloonTips
	lng_MainGUI							= Settings-window
	lng_DuplicateHotkey				= ### is already in use by:
	lng_DuplicateWinHotkey			= ##1 is a standard hotkey of ##2.`nActually it is assigned to:
	lng_OverwriteWinHotkey			= Do you want to use this hotkey and overwrite its standard assignment?
	lng_DuplicateHotkeys				= The following hotkeys are use by more than one extension. Only the first one will be used. Double click opens the affected extension.
	lng_DuplicateTitle				= Conflict in hotkeys
	lng_DuplicateCol1					= Extension
	lng_DuplicateCol2					= Hotkey
	lng_DuplicateCol3					= Function
	lng_DuplicateTempHotkey			= ### is an already assigned but not confirmed hotkey
	lng_OverwriteDupHotkey			= Do you want to assign the entered hotkey and`ndelete the hotkey form the extension shown above?
	lng_Chapter							= Chapter:
	lng__Devel							= Development-mode (ac'tivAid reloads automatically, if a script-file has been updated)
	lng_WritingSettings				= Saving settings ...
	lng_requires						= requires
	lng_requiresAddMsg				= This extension requires the following extension to be installed:`n
	lng_requiresRemMsg				= This extension can't be uninstalled because it's required by the following extensions:`n
	lng_getClassMsg					= Please position the mouse-cursor over a windows-control`nor title bar (= whole window) and press Enter. (ESC = cancel)
	lng_getWindowClassMsg			= Please position the mouse-cursor over`na window and press Enter. (ESC = cancel)
	lng_Loading							= reloading %ScriptNameFull% ...
	lng_Apply							= &Apply
	lng_installed						= installed
	lng_available						= available
	lng_exit								= &Exit
	lng_Left								= left
	lng_Right							= right
	lng_Middle							= middle
	lng_MouseButton					= Mousebutton
	lng_Key								= key
	lng_KbRelease						= release
	lng_KbAppsKey						= AppsKey
	lng_KbWin							= Windows
	lng_KbAlt							= Alt
	lng_KbShift							= Shift
	lng_KbShiftShort					= Sh
	lng_KbCtrl							= Ctrl
	lng_KbCapsLock						= CapsLock
	lng_KbNumpad						= Numpad
	lng_KbNumpadShort					= Num
	lng_KbScrollLock					= ScrollLock
	lng_KbPgUp							= Page up
	lng_KbPgDn							= Page down
	lng_KbEnd							= End
	lng_KbDot							= Dot
	lng_KbDel							= Del
	lng_KbHome							= Home
	lng_KbIns							= Ins
	lng_KbClear							= Clear
	lng_KbPrintScreen					= Print
	lng_KbCtrlBreak					= Break
	lng_KbBackspace					= Backspace
	lng_KbSpace							= Space
	lng_KbEnter							= Enter
	lng_KbTab							= Tab
	lng_KbPause							= Pause
	lng_KbCurUp							= Cursor up
	lng_KbCurDown						= Cursor down
	lng_KbCurLeft						= Cursor left
	lng_KbCurRight						= Cursor right
	lng_KbHelp							= Help
	lng_KbSleep							= Standby
	lng_KbBrowser_Back				= Browser Back
	lng_KbBrowser_Forward			= Browser Forward
	lng_KbBrowser_Refresh			= Browser Refresh
	lng_KbBrowser_Stop				= Browser Cancel
	lng_KbBrowser_Search				= Browser Search
	lng_KbBrowser_Favorites			= Browser Favorites
	lng_KbBrowser_Home				= Browser Home
	lng_KbVolume_Mute					= Volume mute
	lng_KbVolume_Down					= Volume down
	lng_KbVolume_Up					= Volume up
	lng_KbMedia_Next					= Media Next
	lng_KbMedia_Prev					= Media Previous
	lng_KbMedia_Stop					= Media Stop
	lng_KbMedia_Play_Pause			= Media Play/Pause
	lng_KbLaunch_Mail					= Start Mail
	lng_KbLaunch_Media				= Start Media
	lng_KbLaunch_App1					= Start App1
	lng_KbLaunch_App2					= Start App2
	lng_KbWheelUp						= Wheel up
	lng_KbWheelDown					= Wheel down
	lng_KbLButton						= Left mouse button
	lng_KbRButton						= Right mouse button
	lng_KbMButton						= Middle mouse button
	lng_Readme							= Help
	lng_FAQ								= Also take a look at the FAQ on www.heise.de (German)
	lng_Changelog						= Changes
	lng_ViewChangelog					= What's new?
	lng_Browse							= &Browse ...
	lng_CustomWorkingDir				= Working directory
	lng_activated						= active
	lng_activate						= activate
	lng_deactivated					= inactive
	lng_cancel							= Cancel
	lng_Default							= Default
	lng_Close							= Close
	lng_OK								= OK
	lng_Hotkey							= Hotkey
	lng_Hotkeys							= Hotkeys
	lng_Command							= Command
	lng_SettingsMenu					= 8
	lng_DefaultSettings				= Reset ### to default settings
	lng_ExportSettings				= Export ### settings
	lng_ImportSettings				= Import ### settings
	lng_AddSettings					= add ### settings
	lng_ResetWindows					= Reset all windows from ###
	lng_AskResetWindows				= Do you really want to reset all windows from ###?
	lng_ExportAsk						= Do you really want to export the settings of the shown extension?`nUnconfirmed changes (with OK) won't be exported.
	lng_ImportAsk						= Importing will overwrite all settings of the shown extension`nDo you really want to import?
	lng_ImportAsk2						= Importing will overwrite all settings of the shown extension`nUnconfirmed changes (with OK) won't be exported.`nDo you really want to import?
	lng_AddAsk							= Do you really want to add the settings?`nOnly non-existent settings will be added.
	lng_ImportImpossible				= Wrong settings-file, it does no match to the extension!
	lng_SaveAllSettings				= save all settings-files to a folder
	lng_LoadAllSettings				= load all settings-file from a folder
	lng_SaveAllAsk						= Select the folder wher to save all settings-files.`nUnconfirmed changes (with OK or Apply) won't be exported.
	lng_LoadAllAsk						= Select the folder with saved settings. THIS WILL OVERWRITE ALL OF YOU CURRENT SETTINGS.
	lng_DefaultMsg						= Should the settings of the shown extension really be set to default?`nAttention: unconfirmed changes (with OK) get lost.
	lng_SettingsNotApplied			= ac'tivAid must be reloaded, unconfirmed`nchangeds (with OK or Apply) won't be saved.`n`nDo you want to continue?
	lng_PleaseApplySettings			= Please save all settings with OK or Apply!
	lng_ExtensionManagerHelp		= Installed extensions possibly have to be activated in the settings-window or the tray-menu`n`nAll 'available extensions' won't be loaded with ac'tivAid and have to be installed here if you want to use them.
	lng_DuplicateExtensions			= These extensions have the same extension name and one file should be modified or deleted
	lng_Settings						= %ScriptName%
	lng_IsInList						= The selected folder already exist in the list!
	lng_HasSubfolder					= There are sub-folders from the selected folder in the list!`nYou have to remove them first.
	lng_IsSubfolder					= The selected folder or is a sub-folder of:
	lng_EnableDisable					= Enable/disable extension
	lng_ShowHotkeyList				= Show overview of all hotkeys
	lng_HotkeyListAOT					= Show hotkey list always on top
	lng_CreatingHotkeyList			= Creating hotkey list ...
	lng_ShowMainContextMenu			= Context menu with all functions
	lng_NoTrayIcon						= No tray-icon (Attention: with this option the settings are only accessible via the hotkey)
	lng_Betatester						= Also load beta-versions, which could contain expected bugs
	lng_ManualUpdate					= Manual update
	lng_ManualUpdateText				= If the automatic update fails (blocked by a proxy), you have to download and install the latest version manually. The latest version can be downloaded at:
	lng_OpenURLAndExit				= Open website and quit ac'tivAid
	lng_SelectLanguage				= Select language / Sprache wählen
	lng_RunAsAdmin						= Start ac'tivAid with administrator rights
	lng_NeedAdminRights				= ac'tivAid needs administrator rights
	lng_NeedUserPass					= Please enter the password of the current user
	lng_LeaveAdmin						= Leave administrator mode
	lng_LeaveAdminCantReload		= ac'tivAid won't reload when leaving the admin-mode.`nYou have to run ac'tivAid manually.
	lng_UserMode00						= Activate single user-mode
	lng_UserMode10						= Single user-mode, Admin
	lng_UserMode01						= Activate multi user-mode
	lng_UserMode11						= Multi user-mode, Admin
	lng_UserMode001					= Activate USB/portable standard-mode
	lng_UserMode101					= USB/portable standard-mode, Admin
	lng_UserMode011					= activate USB/portable multi-computer-mode
	lng_UserMode111					= USB/portable multi-computer-mode, Admin
	lng_CheckYourFolderOptions		= Please configure windows explorer to show the`nfull path either in the window-title or the address-bar.
	lng_ChangeDirFailed				= Changing a directory does only work if an explorer-window with address-bar or a file-dialog is active.
	lng_FolderDoesNotExist			= The directory does not exist:
	lng_AdminAttention				:= "  Attention: ac'tivAid is running with administrator rights`n  Please leave the admin mode as soon as possible (ac'tivAid menu)!"
	lng_AdminAttentionAsk			= Would you like to immediatly reload ac'tivAid and`n  leave the admin mode?
	lng_DisableToggleLayout			= The system hotkey for changing the keyboard layout (Alt+Shift) is active.`nIn combination with ac'tivAid (respectively AutoHotkey) this could result in unexpected layout switches.`nIt is a well known problem and you'll never see this message again.`n`nShall ac'tivAid deacativate the system hotkey? (Registry will be change)
	lng_AskUninstall					= Do you really want to uninstall ac'tivAid and the user-settings?`n`nThe following directories will be removed:`n
	lng_UninstallFinished			= ac'tivAid has been successfully uninstalled!`nFiles that couldn't be deleted will be deleted at the next system-start.
	lng_CreateUninstaller			= ac'tivAid has been started the first time.`n`nShould a program group be created and ac'tivAid be added to Control Panel/Software`nso it can be easily uninstalled?`n`nThis will modify the Registry.
	lng_noUninstallerInsideActivaid			= There is no uninstall routine inside ac'tivAid any longer
	lng_by								= by
	lng_Help								= Help
	lng_ContextHelp					= Help about ###
	lng_activAidHomepage				= visit the official ac'tivAid-website
	lng_Bugtracker						= visit support-website (bugtracker)
	lng_Contact							= email-contact (activaid@heise.de)
	lng_About							= About %ScriptNameFull% ...
	lng_about_main_developer		= Main developers`n(core and extensions)
	lng_about_ext_developer			= Extension developers
	lng_OpenSettingsDir				= open 'settings'-folder
	lng_CopySettingsToSingle		= Export all settings to the single user-mode
	lng_CopySettingsToSingleAsk	= All settings will be overwritten when you export`nthe settings to the single user-mode!`nDo you really want to export the settings?
	lng_CopyUSBSettingsToSingle	= Export all settings to the USB/Portable standard-mode
	lng_CopyUSBSettingsToSingleAsk= All settings will be overwritten when you export`nthe settings to the USB/Portable standard-mode!`nDo you really want to export the settings?
	lng_CopySettingsToUser			= Import all settings from the single user-mode
	lng_CopySettingsToUserAsk		= All settings of the current user will be overwritten`nwhen you import the settings from the single user-mode!`nDo you really want to import the settings?
	lng_CopyUSBSettingsToUser		= Import all settings from the USB/Portable standard-mode
	lng_CopyUSBSettingsToUserAsk	= All settings for the current computer will be overwritten`nwhen you import the settings from the USB/Portable standard-mode!`nDo you really want to import the settings?
	lng_CopySettingsFromUser		= Import all settings from %A_Username%
	lng_CopySettingsFromUserAsk	= All settings will be overwritten when you`nimport the settings from %A_Username%!`nDo you really want to import the settings?
	lng_CopyUSBSettingsFromUser	= Import all settings from ComputerSettings\%A_Computername%
	lng_CopyUSBSettingsFromUserAsk= All settings of the current computer will be overwritten`nwhen you import the settings from ComputerSettings\%A_Computername%!`nDo you really want to import the settings?
	lng_AlternativeTrayMenu			= The menue items of the tray-menu will show the settings-window of the corresponding extension
	lng_AddUninstaller				= Create uninstall-entry and program group
	lng_RemoveUninstaller			= Remove uninstall-entry and program group
	lng_AddUninstallerFailure		= Uninstall-entry and ac'tivAid program group could not be created.`nYou enventually need to start ac'tivAid in adminstator mode.
	lng_RemoveUninstallerFailure	= Uninstall-entry and ac'tivAid program group could not be removed.`nYou enventually need to start ac'tivAid in adminstator mode.
	lng_AddUninstallerSuccess		= Uninstall-entry and ac'tivAid program group has been created.
	lng_RemoveUninstallerSuccess	= Uninstall-entry and ac'tivAid program group has been removed.
	lng_None								= (none)
	lng_DisableOthers					= Disable all other extensions
	lng_EnableAll						= Enable all extensins
	lng_RemoveFromGUI					= Remove ### from configuration
	lng_RemovedExtensions			= restore removed extensions...
	lng_Search							= Search term
	lng_PortableExe					= You probably want to start Portable ac'tivAid, but you accidentally launched "ac'tivAid.ahk". To enable the protable mode you have to launch "Portable_ac'tivAid.exe"! To avoid this message, you have to delete or rename that file.
	lng_WrongAHKVersion				= AutoHotkey %neededAHKversion% or higher is need to run ac'tivAid.`nPlease install the latest Version of AutoHotkey.`n`nIf you use ac'tivAid's automatic update, AutoHotkey will also be updated.
	lng_BackupOnUpdate				= Create a backup of the ac'tivAid folder before updating
	lng_Show								= Show ...
	lng_On								= On
	lng_Off								= Off
	lng_AnotherActivAidActive		= There are other ac'tivAid processs running.`nConcurrent processes will cause unpredictable problems.`nDo you really want to start another ac'tivAid process?
	lng_NewSettingsDirForVista		= Windows Vista and future Windows Versions do not allow programs to write to their own folder.`nBecause of this settings will for the single user-mode will be copied from:`n%A_ScriptDir%\settings`nto:`n%A_AppDataCommon%\ac'tivAid\settings

	lng_StatisticsToClipboard		= Copy to clipboard (incl. additional infos)
	lng_ReloadFailed					= Can't reload ac'tivAid.`nMaybe an error occured or ac'tivAid was too busy.
	lng_NoExtensionsInstalled		= <-+------------------------------------------------------------------------+`n  | There are no extensions installed yet. Without installed extensions      |`n  | ac'tivAid won't be very userful. Please select the category            |`n  | 'extensions' in the left category list to install extensions.            |`n  +------------------------------------------------------------------------+`n`n`n

	lng_Second							= second
	lng_Seconds							= seconds
	lng_Minute							= minute
	lng_Minutes							= minutes
	lng_Hour								= hour
	lng_Hours							= hours
	lng_Day								= day
	lng_Days								= days
	lng_Month							= month
	lng_Months							= months
	lng_Year								= year
	lng_Years							= years

	lng_Statistics						= Statistic and informations
	lng_StatFirstLaunch				= First time launch
	lng_StatLastLaunched				= Last time launched
	lng_StatLaunchCount				= Number of starts
	lng_StatReloadCount				= Number of reloads
	lng_StatUpdateCount				= Number of updates
	lng_StatExitCount					= Number of regular exits
	lng_StatTotalTime					= Total running time
	lng_StatSessionTime				= Running time of this session
	lng_StatLongestSession			= Longest session
	lng_StatVersion					= ac'tivAid version
	lng_StatAHKVersion				= AutoHotkey version
	lng_StatOS							= Operating system
	lng_StatCompOS							= Compatibility mode
	lng_StatUser						= User name
	lng_StatComputer					= Computer name
	lng_StatIP							= IP addresse
	lng_StatCompiled					= , compiled
	lng_StatMode						= Mode
	lng_StatSettingsDir				= Settings-Directory
	lng_StatWriteLocked				= (locked or no rights)
	lng_StatExtendRButton			= Extends richt mouse button
	lng_StatExtendMButton			= Extends middle mouse button
	lng_StatLoadingTime				= Loading time (duration)
	lng_Network							= Network
	lng_AdditionalSettings			= Additional settings
	lng_CleanINI						= Clean up settings file
	lng_CleanINIAsk					= The settings file will be deleted and recreated.`nac'tivAid saves all settings of the installed extensions`ninto the fresh settings file and will reload.`nYou'll lose all settings from uninstalled extensions.

	lng_VarDump							= Show internal variables

	lng_GlobalProxySettings			= Global Proxy settings
	lng_ProxyType						= Type
	lng_ProxyHistory					= History
	lng_ProxyHistoryHeaders			= URL|Local|Time|Speed
	lng_UseProxy						= Use Proxy for ###
	lng_GlobalDownloadFolder		= Default download folder
	lng_Username						= User
	lng_Password						= Password

	lng_ExtensionConflict			= Failed to load all installed extensions.`nac'tivAid will reload now to solve this problem.
	lng_ExtensionConflictDuplicates = Duplicate extensions found.`nac'tivAid will reload now to solve this problem.
	lng_ExtensionMissingQuickNote	= At least one QuickNote scripts is not available. Trying to duplicate original script.

	tooltip_Hotkey_					= Click to assign a hotkey.`nClick with Shift or Alt to assign mouse or joystick hotkeys.
	tooltip_Autostart					= Off = removes the shortcut from the autostart-folder`nOn = creates a shortcut to ac'tivAid in the autostart-folder`nGrey/Green = additionally adds the parameter 'nosplash' to hide the startup-screen
	tooltip_searchTermReadme		= F3 - search next`nShift+F3 - search previous
	tooltip_searchTermChangeLog	= %tooltip_searchTermReadme%
	tooltip_searchTermContextHelp	= %tooltip_searchTermReadme%
	tooltip_searchTermHotkeyList	= %tooltip_searchTermReadme%
	tooltip_searchButtonReadme		= %tooltip_searchTermReadme%
	tooltip_searchButtonChangeLog	= %tooltip_searchTermReadme%
	tooltip_searchButtonContextHelp	= %tooltip_searchTermReadme%
	tooltip_searchButtonHotkeyList= %tooltip_searchTermReadme%

	AdminGroup							= Administrators

	ReadMeFile							= %A_ScriptDir%\ac'tivAid Readme.txt
	ChangeLogFile						= %A_ScriptDir%\ac'tivAid Changelog.txt

	lng_useGdiPlus						= Use GDI+ for visual effects (If your OS is not XP or newer then you will need gdiplus.dll)
	lng_sub_gdip_configGui			= Configure GDIplus
	lng_gdip_backgroundColor		= Background color
	lng_gdip_backgroundColor2		= Sec. Background color
	lng_gdip_borderColor				= Border color
	lng_gdip_rounding					= Rounding
	lng_gdip_trans						= Transparency
	lng_gdip_osd						= Visuals
	lng_gdip_generalSettings		= General
	lng_gdip_fontFamily				= Standard
	lng_gdip_fontFamilyTitle		= Title
	lng_gdip_fontFamilyHeader		= Header
	lng_gdip_fontSize					= Size
	lng_gdip_fontColor				= Color
	lng_gdip_monitor					= Monitor
	lng_gdip_monitorList				= Primary|Mouse|Active Window
	lng_gdip_posHorList				= Left|Center|Right
	lng_gdip_posVerList				= Top|Center|Bottom
	lng_gdip_position					= Position

	lng_OSDTips							= OSD instead of balloon tips
	lng_OSDIcons						= Show OSD-Icons

	lng_GdiPnotFoundTitle			= GDI+ not found
	lng_GdiPnotFound					= Please download gdiplus.dll and save at %A_WinDir%\System32.`nOpen browser with download location?

	lng_playSound						= Play Sound
}

; Sprachunabhängige Variablen:
lng_about_main_developer_list	= Michael Telgkamp`nJack Tissen`nEric Werner`nWolfgang Reszel
lng_about_ext_developer_list	= Robert Deimel`nPatrick Eder`nJossekin Beilharz`nDavid Hilberath`nHolomind`njla`nChris Mallett`nStephan Noy`nOliver Pfeiffer`nWerner Piel`nBernd Schandl`nFlorian Schenk`nDirk Schwarzmann`nElmar Sonnenschein`nAlexander Taubenkorb`nwOxxOm

lng_KbSC105 = [Messenger/Files]
lng_KbSC107 = [Redo]
lng_KbSC108 = [Undo]
lng_KbSC10a = [Paste]
lng_KbSC10b = [Scroll Up]
lng_KbSC111 = [Scroll Up fast]
lng_KbSC112 = [Scroll Up faster]
lng_KbSC113 = [Word]
lng_KbSC114 = [Excel]
lng_KbSC115 = [Calendar]
lng_KbSC116 = [Log Off]
lng_KbSC117 = [Cut]
lng_KbSC118 = [Copy]
lng_KbSC11f = [Scroll Up fastest]
lng_KbSC121 = [Calculator]
lng_KbSC123 = [Spell/Paste]
lng_KbSC125 = [Cut]
lng_KbSC126 = [Copy]
lng_KbSC13b = [Help]
lng_KbSC13c = [My Music/Office]
lng_KbSC13d = [Task Pane]
lng_KbSC13e = [New]
lng_KbSC13f = [Open]
lng_KbSC140 = [Close]
lng_KbSC141 = [Reply]
lng_KbSC142 = [Fwd]
lng_KbSC143 = [Send]
lng_KbSC157 = [Save]
lng_KbSC158 = [Print]
lng_KbSC15e = [Power]
lng_KbSC15f = [Sleep]
lng_KbSC164 = [My Pictures]
lng_KbSC16b = [My Computer]
lng_KbSC18b = [Scroll Down]
lng_KbSC191 = [Scroll Down fast]
lng_KbSC192 = [Scroll Down faster]
lng_KbSC19f = [Scroll Down fastest]


IfNotExist, %ReadMeFile%
	ReadMeFile	= %A_ScriptDir%\ac'tivAid LiesMich.txt
IfNotExist, %ChangeLogFile%
	ReadMeFile	= %A_ScriptDir%\ac'tivAid Änderungen.txt
